### ISSUE TITLE
PR for PyTorch 1.+ and Python 3 support

### ISSUE THREAD

**Issue by martinengelcke** [riannevdberg/sylvester-flows#2]
Hi Rianne,

Thank you for this really nice code release :)

I cloned the repo and made some changes so that it runs with PyTorch 1.+ and Python 3. Also solved the issue mentioned in #1 . I tested the changes on MNIST (binary input) and Freyfaces (multinomial input), giving similar results to the original code.

If you are interested in reviewing and potentially adding this to the repo, I would be happy to clean things up and make a PR.

Best,
Martin

**Comment by riannevdberg** [comment]
Hi Martin, 

That's great! I would definitely be interested in adding this to the repo, I'll wait for a PR then.

Best,
Rianne
